# Generated by Django 6.0.6 on 2026-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_attacker_hostnames_attacker_open_ports_attacker_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('attackers', models.ManyToManyField(related_name='cves', to='intel.attacker')),
            ],
        ),
        migrations.CreateModel(
            name='MitreTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tactics', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('attackers', models.ManyToManyField(related_name='techniques', to='intel.attacker')),
            ],
        ),
    ]
