# Generated by Django 6.0.6 on 2026-07-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0003_cve_mitretechnique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitretechnique',
            old_name='tactics',
            new_name='tactic',
        ),
    ]
