# Generated by Django 6.0.6 on 2026-07-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacker',
            name='hostnames',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='attacker',
            name='open_ports',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='attacker',
            name='org',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attacker',
            name='vt_malicious_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attacker',
            name='vt_reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attacker',
            name='vt_suspicious_votes',
            field=models.IntegerField(default=0),
        ),
    ]
